[background]
cycle_timeout = 150
fade_duration = 1000
fill_mode = stretch
image = /home/conzxy/Pictures/shiny-colors/linze/bg
randomize = true

[dock]
adjacent_edge_hotspot_size = 20
autohide = false
autohide_duration = 0
autohide_hide_delay = 300
autohide_show_delay = 100
css_path = 
dock_height = 100
edge_hotspot_size = 20
edge_margin = 0
edge_offset = 20
full_span = false
icon_height = 72
max_per_line = 0
minimal_height = 100
minimal_width = 100
mirror_margin = true
position = bottom
show_close = true

[locker]
background_color = \#0000
background_image = true
battery_always = false
battery_description_font = 0em default
battery_enable = false
battery_icon_size = 3.000000
battery_percent_font = 3em default
battery_position = top-left
battery_status = percentage
clock_always = true
clock_enable = true
clock_font = 3em default
clock_format = %H:%M%n<span font-size='xx-small'>%e %b %Y</span>
clock_position = top-center
fingerprint_always = false
fingerprint_enable = false
fingerprint_font = 2em default
fingerprint_icon_size = 10.000000
fingerprint_overlay_icon_size = 7.000000
fingerprint_position = bottom-center
hide_anim = 1
hide_anim_dur = 0.400000
hide_time = 5.000000
instant_unlock_always = false
instant_unlock_enable = false
instant_unlock_font = default
instant_unlock_position = bottom-center
lockout_attempts = 5
lockout_timer = 10
mpris_always = true
mpris_control = false
mpris_enable = true
mpris_font = 1em default
mpris_format = Now Playing:%n%track%n%album%n%artist
mpris_icon_size = 5.000000
mpris_position = bottom-right
network_always = false
network_enable = false
network_font = 2em default
network_icon_size = 1.000000
network_position = top-right
password_always = false
password_enable = true
password_position = center-center
pin_always = false
pin_enable = false
pin_pad_font = 2em default
pin_position = bottom-center
pin_reply_font = 2em default
prewake = 1.000000
user_always = true
user_enable = true
user_font = 3em default
user_icon_size = 10.000000
user_position = center-center
volume_always = false
volume_enable = false
volume_icon_size = 2.000000
volume_position = top-right
weather_always = false
weather_enable = false
weather_font = 4em default
weather_icon_size = 5.000000
weather_position = bottom-left

[panel]
adjacent_edge_hotspot_size = 20
autohide = true
autohide_duration = 300
autohide_hide_delay = 500
autohide_show_delay = 300
background_color = gtk_headerbar
battery_font = default
battery_icon_invert = true
battery_icon_size = 24
battery_status = 1
brightness_icon_size = 0
brightness_invert_scroll = false
brightness_popup_on_change = true
brightness_popup_timeout = 2.500000
brightness_scroll_sensitivity = 1.000000
brightness_slider_length = 300
brightness_spacing = 8
center = false
clock_font = default
clock_format = %e %A %H:%M
commands_output_max_chars = 10
css_path = 
default_icon_size = 48
edge_hotspot_size = 20
edge_margin = 0
edge_offset = 20
force_show_popup = true
full_span = true
hibernate_command = systemctl hibernate
launchers_animation_duration = 200
launchers_rows_cols = 1
launchers_size = 42
launchers_spacing = 4
layer = top
logout_command = wayland-logout
menu_category_icon_size = 48
menu_fuzzy_search = true
menu_icon = 
menu_icon_size = 0
menu_item_icon_size = 48
menu_item_spacing = 8
menu_list = false
menu_logout_command = 
menu_min_category_width = 200
menu_min_content_height = 500
menu_min_content_width = 500
menu_show_categories = false
menus_change_motion = false
middle_click_close = true
minimal_height = 24
minimal_width = 35
mirror_margin = true
mixer_icon_size = 0
mixer_icons_on_left = false
mixer_invert_scroll = false
mixer_layout = horizontal
mixer_left_click_action = show_mixer
mixer_middle_click_action = mute_quick_target
mixer_popup_icon_size = 0
mixer_popup_on_change = true
mixer_popup_timeout = 2.500000
mixer_quick_target_choice = default_sink
mixer_right_click_action = show_quick_target
mixer_scroll_sensitivity = 1.000000
mixer_slider_length = 300
mixer_spacing = 8
network_icon_invert_color = false
network_icon_size = 32
network_no_label = false
network_onclick_command = default
network_status = 1
network_status_font = default
network_status_use_color = false
notifications_autohide_timeout = 2.500000
notifications_critical_in_dnd = true
notifications_icon_size = 0
outputs = *
position = bottom
reboot_command = systemctl reboot
shutdown_command = systemctl poweroff
suspend_command = systemctl suspend
switchuser_command = dm-tool switch-to-greeter
tray_icon_size = 0
tray_menu_on_middle_click = false
tray_rows_cols = 1
tray_spacing = 5
volume_display_timeout = 2.500000
volume_icon_size = 0
volume_scroll_sensitivity = 0.050000
weather_font = default
widgets_center = window-list
widgets_left = menu
widgets_right = notifications
window_list_icon_size = 16
window_list_live_window_previews = true
window_list_size = 192
workspace_switcher_layout = row
workspace_switcher_render_views = true
workspace_switcher_target_size = 0.000000

[app_id_map_for_desktop]
# app_id -> desktop name
steam_app_2340875539 = genshin-impact
steam_app_3841395391 = zenless-zone-zero
md.obsidian.Obsidian = obsidian
wechat = wechat-universal
steam_proton = bottles-Neeview-NeeView
