#!/bin/python3

from PIL import Image
from sys import argv
from os import path
import os

def convert_image_to(source_image_filename: str, output_format: str):
    extension_pos = source_image_filename.rfind('.')
    if extension_pos == -1:
        return
    try:
        image = Image.open(source_image_filename)
    
        output_image_filename = source_image_filename[:extension_pos] + '.' + output_format
        if output_image_filename == source_image_filename or path.exists(output_image_filename):
            print("output image file exitst: ", output_image_filename)
            return
        else:
            print("output image file: ", output_image_filename)
        image.save(output_image_filename)
    except:
        print("{} is not a valid image file".format(source_image_filename))

if __name__ == "__main__":
    if len(argv) < 3:
        print("Usage: {} source(directory or image) image_format".format(argv[0]))
        exit(0)

    source = argv[1]
    image_fmt = argv[2]
    if (path.isdir(source)):
        image_filenames = os.listdir(source)
        for image_filename in image_filenames:
            convert_image_to(image_filename, image_fmt)
    else:
        convert_image_to(source, image_fmt)        
