#!/bin/python3
import sys
from sys import argv
import os

if __name__ == "__main__":
    if len(argv) < 2:
        print("Usage: {} *.zip".format(argv[0]))
        exit(0)

    zip_archive = sys.argv[1]
    extension_pos = zip_archive.rfind(".zip")
    if extension_pos == -1:
        print("ERROR: not a valid zip file")
        exit(0)
    output_dir = zip_archive[:extension_pos]
    print("output_dir = ", output_dir)
    os.system("unzip '{}' -d '{}'".format(zip_archive, output_dir))
